"""Measure a corpus before designing anything around it. SPEC.md 2, 8a.

§8a promises the corpus profile regenerates from a command rather than by hand,
so that a stale figure cannot survive a corpus swap. That was not true when it
was written — the original profile came from a throwaway diagnostic — and the
§8a swap is what made the gap matter. This is the command.

    uv run python scripts/profile_corpus.py data/raw > docs/corpus-profile.md
"""

from __future__ import annotations

import argparse
import collections
import statistics
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from recall.ingestion.classify import classify  # noqa: E402
from recall.ingestion.pdf import load  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Profile a corpus of PDFs.")
    parser.add_argument("directory", type=Path, nargs="?", default=Path("data/raw"))
    args = parser.parse_args(argv)

    files = sorted(args.directory.glob("*.pdf"))
    if not files:
        parser.error(f"no PDFs in {args.directory}")

    rows = []
    agree = compared = 0
    for path in files:
        document = load(path)
        pages = document.text_pages
        kind = classify(document)
        words = [p.n_words for p in pages]
        rows.append(
            {
                "name": path.name,
                "type": kind.doc_type,
                "pages": len(document.pages),
                "text_pages": len(pages),
                "words": sum(words),
                "median": statistics.median(words) if words else 0,
                "landscape": sum(1 for p in pages if p.is_landscape),
            }
        )
        # §2a's title-heuristic agreement, recomputed rather than carried over.
        for page in pages:
            if kind.doc_type != "deck" or not page.lines:
                continue
            compared += 1
            largest = max(page.spans, key=lambda s: s.size, default=None)
            if largest is not None and largest.text.strip() == page.lines[0].strip():
                agree += 1

    by = collections.defaultdict(list)
    for r in rows:
        by[r["type"]].append(r)

    total_pages = sum(r["pages"] for r in rows)
    total_words = sum(r["words"] for r in rows)
    print("# Corpus profile\n")
    print("Measured, not assumed. Regenerated by `scripts/profile_corpus.py`, so a")
    print("figure here cannot outlive the corpus it describes — see SPEC.md 8a.\n")
    print(f"**Snapshot: {date.today().isoformat()} — {len(rows)} files, "
          f"{total_pages} pages, {total_words:,} words.**\n")
    print("## What the corpus is\n")
    print("| Type | Files | Pages | Words | Median words/page |")
    print("|---|---|---|---|---|")
    for kind in sorted(by):
        rs = by[kind]
        meds = [r["median"] for r in rs if r["median"]]
        print(f"| {kind} | {len(rs)} | {sum(r['pages'] for r in rs)} | "
              f"{sum(r['words'] for r in rs):,} | "
              f"{statistics.median(meds) if meds else 0:.0f} |")
    text_pages = sum(r["text_pages"] for r in rows)
    print(f"\n{total_pages - text_pages} of {total_pages} pages carry no text layer.")
    landscape = sum(r["landscape"] for r in rows)
    print(f"{landscape} of {text_pages} text-bearing pages are landscape.\n")
    if compared:
        print(f"**Title heuristics agree on {agree / compared:.0%} of {compared} "
              f"slides** — the font-based rule (largest span) against the "
              f"plain-text one (first line). SPEC.md 2a turns on this figure.\n")
    print("## Every file\n")
    print("| File | Type | Pages | Words | Median words/page |")
    print("|---|---|---|---|---|")
    for r in rows:
        print(f"| {r['name']} | {r['type']} | {r['pages']} | {r['words']:,} | {r['median']:.0f} |")
    return 0


if __name__ == "__main__":
    sys.exit(main())
